"""
EXPANDED COMPANY LIST - 750+ COMPANIES FOR DATA MOAT
=====================================================
Import this in global_csr_spider.py as:
from company_list_expanded import COMPANIES
"""
from typing import List, Tuple

# 750+ Companies for maximum CSR data coverage
COMPANIES: List[Tuple[str, str]] = [
    # =========================================================================
    # MENA - 80+ Companies
    # =========================================================================
    # UAE - Core
    ("ADNOC", "https://www.adnoc.ae/en/sustainability"),
    ("ADNOC Distribution", "https://www.adnocdistribution.ae/en/sustainability"),
    ("Borouge", "https://www.borouge.com/sustainability"),
    ("ENOC", "https://www.enoc.com/en/sustainability"),
    ("DEWA", "https://www.dewa.gov.ae/en/about-us/sustainability"),
    ("Emirates Global Aluminium", "https://www.ega.ae/en/sustainability"),
    ("DP World", "https://www.dpworld.com/sustainability"),
    ("Masdar", "https://masdar.ae/en/about-masdar/sustainability"),
    ("Mubadala", "https://www.mubadala.com/en/sustainability"),
    ("TAQA", "https://www.taqa.com/sustainability"),
    ("Emirates", "https://www.emirates.com/ae/english/about-us/sustainability"),
    ("Etihad Airways", "https://www.etihad.com/en/about-us/sustainability"),
    ("Etihad Rail", "https://www.etihadrail.ae/sustainability"),
    ("Emaar", "https://www.emaar.com/en/sustainability"),
    ("Aldar Properties", "https://www.aldar.com/en/sustainability"),
    ("DAMAC", "https://www.damacproperties.com/sustainability"),
    ("Etisalat", "https://www.etisalat.ae/en/sustainability"),
    ("du Telecom", "https://www.du.ae/sustainability"),
    ("Emirates NBD", "https://www.emiratesnbd.com/en/sustainability"),
    ("First Abu Dhabi Bank", "https://www.bankfab.com/sustainability"),
    ("ADCB", "https://www.adcb.com/en/sustainability"),
    ("ADDC", "https://www.addc.ae/en/sustainability"),
    ("Senaat", "https://www.senaat.ae/sustainability"),
    ("EDGE", "https://www.edgegroup.ae/sustainability"),
    ("Dubai Holding", "https://www.dubaiholding.com/sustainability"),
    ("Dubai Investments", "https://www.dubaiinvestments.com/sustainability"),
    ("RAK Ceramics", "https://www.rakceramics.com/sustainability"),
    ("AGTHIA", "https://www.agthia.com/sustainability"),
    ("Julphar", "https://www.julphar.net/sustainability"),
    
    # Saudi Arabia - Expanded
    ("Aramco", "https://www.aramco.com/en/sustainability"),
    ("SABIC", "https://www.sabic.com/en/sustainability"),
    ("Ma'aden", "https://www.maaden.com.sa/en/sustainability"),
    ("ACWA Power", "https://www.acwapower.com/sustainability"),
    ("Saudi Electricity", "https://www.se.com.sa/en/sustainability"),
    ("STC", "https://www.stc.com.sa/sustainability"),
    ("Almarai", "https://www.almarai.com/sustainability"),
    ("Sadara Chemical", "https://www.sadara.com/sustainability"),
    ("SAFCO", "https://www.safco.com.sa/sustainability"),
    ("Yansab", "https://www.yansab.com/sustainability"),
    ("TASNEE", "https://www.tasnee.com/sustainability"),
    ("Marafiq", "https://www.marafiq.com.sa/sustainability"),
    ("Saudi Cement", "https://www.saudicement.com.sa/sustainability"),
    ("Yanbu Cement", "https://www.yanbucement.com/sustainability"),
    ("Sipchem", "https://www.sipchem.com/sustainability"),
    ("Mobily", "https://www.mobily.com.sa/sustainability"),
    ("Zain KSA", "https://www.sa.zain.com/sustainability"),
    ("Al Rajhi Bank", "https://www.alrajhibank.com.sa/sustainability"),
    ("SNB", "https://www.alahli.com/sustainability"),
    ("Riyad Bank", "https://www.riyadbank.com/sustainability"),
    ("PIF", "https://www.pif.gov.sa/sustainability"),
    ("Petro Rabigh", "https://www.petrorabigh.com/sustainability"),
    ("Zamil Industrial", "https://www.zamilsteel.com/sustainability"),
    
    # Qatar
    ("QatarEnergy", "https://www.qatarenergy.qa/en/sustainability"),
    ("Qatar Petroleum", "https://www.qp.com.qa/en/sustainability"),
    ("QAPCO", "https://www.qapco.com.qa/sustainability"),
    ("Industries Qatar", "https://www.iq.com.qa/sustainability"),
    ("Qatar Aluminium", "https://www.qatalum.com/sustainability"),
    ("Qatar Steel", "https://www.qatarsteel.com.qa/sustainability"),
    ("Qatar Airways", "https://www.qatarairways.com/en/sustainability"),
    ("QNB", "https://www.qnb.com/sustainability"),
    ("Ooredoo", "https://www.ooredoo.com/sustainability"),
    ("QEWC", "https://www.qewc.com/sustainability"),
    ("Qatar Gas", "https://www.qatargas.com/sustainability"),
    
    # Kuwait
    ("Kuwait Petroleum", "https://www.kpc.com.kw/sustainability"),
    ("KNPC", "https://www.knpc.com/sustainability"),
    ("PIC Kuwait", "https://www.pic.com.kw/sustainability"),
    ("KIPCO", "https://www.kipco.com/sustainability"),
    ("Zain Kuwait", "https://www.kw.zain.com/sustainability"),
    ("NBK", "https://www.nbk.com/sustainability"),
    ("Kuwait Finance House", "https://www.kfh.com/sustainability"),
    ("Agility", "https://www.agility.com/sustainability"),
    ("Equate", "https://www.equate.com/sustainability"),
    
    # Bahrain
    ("BAPCO", "https://www.bapco.net/sustainability"),
    ("Alba", "https://www.albasmelter.com/sustainability"),
    ("Batelco", "https://www.batelco.com/sustainability"),
    ("Gulf Air", "https://www.gulfair.com/sustainability"),
    ("Bahrain Petroleum", "https://www.bpc.bh/sustainability"),
    ("GPIC", "https://www.gpic.com/sustainability"),
    
    # Oman
    ("OQ Oman", "https://oq.com/en/sustainability"),
    ("PDO", "https://www.pdo.co.om/sustainability"),
    ("Omantel", "https://www.omantel.om/sustainability"),
    ("Bank Muscat", "https://www.bankmuscat.com/sustainability"),
    ("Sohar Aluminium", "https://www.sohar-aluminium.com/sustainability"),
    ("Vale Oman", "https://www.vale.com/oman/sustainability"),
    ("Oman Cement", "https://www.omancement.com/sustainability"),
    
    # Egypt
    ("Egyptian Petrochemicals", "https://www.egyptianpetro.com/sustainability"),
    ("EGAS", "https://www.egas.com.eg/sustainability"),
    ("Orascom Construction", "https://www.orascom.com/sustainability"),
    ("CIB Egypt", "https://www.cibeg.com/sustainability"),
    ("Telecom Egypt", "https://www.te.eg/sustainability"),
    ("Eastern Company", "https://www.easternco.com/sustainability"),
    
    # Jordan/Iraq/Morocco
    ("Arab Potash", "https://www.arabpotash.com/sustainability"),
    ("Aqaba Container Terminal", "https://www.act.com.jo/sustainability"),
    ("Royal Jordanian", "https://www.rj.com/sustainability"),
    ("Basra Oil Company", "https://www.basraoil.com/sustainability"),
    ("OCP Group", "https://www.ocpgroup.ma/sustainability"),
    ("Managem", "https://www.managemgroup.com/sustainability"),
    ("Maroc Telecom", "https://www.iam.ma/sustainability"),
    
    # =========================================================================
    # ASIA-PACIFIC - 200+ Companies
    # =========================================================================
    # China
    ("Sinopec", "https://www.sinopec.com/en/sustainability"),
    ("PetroChina", "https://www.petrochina.com.cn/ptr/xhtml/sustainability"),
    ("CNOOC", "https://www.cnooc.com.cn/col/col6183"),
    ("Baosteel", "https://www.baosteel.com/en/sustainability"),
    ("BYD", "https://www.byd.com/en/sustainability"),
    ("CATL", "https://www.catl.com/en/sustainability"),
    ("Alibaba", "https://esg.alibabagroup.com"),
    ("Tencent", "https://www.tencent.com/en-us/responsibility"),
    ("Huawei", "https://www.huawei.com/en/sustainability"),
    ("Lenovo", "https://www.lenovo.com/sustainability"),
    ("Xiaomi", "https://www.mi.com/global/sustainability"),
    ("JD.com", "https://corporate.jd.com/sustainability"),
    ("Geely", "https://global.geely.com/sustainability"),
    ("SAIC Motor", "https://www.saicmotor.com/english/sustainability"),
    ("China Resources", "https://www.crc.com.hk/en/sustainability"),
    ("Haier", "https://www.haier.com/sustainability"),
    ("CRRC", "https://www.crrcgc.cc/en/sustainability"),
    ("CNPC", "https://www.cnpc.com.cn/en/sustainability"),
    ("Sinochem", "https://www.sinochem.com/en/sustainability"),
    ("Wanhua Chemical", "https://www.whchem.com/sustainability"),
    ("Ganfeng Lithium", "https://www.ganfenglithium.com/sustainability"),
    ("CITIC", "https://www.citic.com/sustainability"),
    ("China Minmetals", "https://www.minmetals.com.cn/sustainability"),
    ("Chinalco", "https://www.chinalco.com.cn/sustainability"),
    ("Jiangxi Copper", "https://www.jxcc.com/sustainability"),
    ("Zijin Mining", "https://www.zijinmining.com/sustainability"),
    ("Tianqi Lithium", "https://www.tianqilithium.com/sustainability"),
    ("LONGi Green", "https://www.longi.com/sustainability"),
    ("JA Solar", "https://www.jasolar.com/sustainability"),
    ("Trina Solar", "https://www.trinasolar.com/sustainability"),
    ("Jinko Solar", "https://www.jinkosolar.com/sustainability"),
    ("Anhui Conch", "https://www.conch.cn/sustainability"),
    ("Sany Heavy", "https://www.sanygroup.com/sustainability"),
    ("XCMG", "https://www.xcmg.com/sustainability"),
    ("Zoomlion", "https://www.zoomlion.com/sustainability"),
    
    # Japan
    ("Toyota", "https://global.toyota/en/sustainability"),
    ("Honda", "https://global.honda/en/sustainability"),
    ("Nissan", "https://www.nissan-global.com/EN/SUSTAINABILITY"),
    ("Sony", "https://www.sony.com/en/SonyInfo/csr"),
    ("Panasonic", "https://holdings.panasonic/global/corporate/sustainability"),
    ("Hitachi", "https://www.hitachi.com/sustainability"),
    ("Mitsubishi", "https://www.mitsubishi.com/en/sustainability"),
    ("Nippon Steel", "https://www.nipponsteel.com/en/csr"),
    ("JFE Steel", "https://www.jfe-steel.co.jp/en/sustainability"),
    ("Sumitomo", "https://www.sumitomocorp.com/en/sustainability"),
    ("Mitsui", "https://www.mitsui.com/jp/en/sustainability"),
    ("Toshiba", "https://www.global.toshiba/sustainability"),
    ("Canon", "https://global.canon/en/sustainability"),
    ("NEC", "https://www.nec.com/en/global/sustainability"),
    ("Fujitsu", "https://www.fujitsu.com/global/about/environment"),
    ("Suzuki", "https://www.globalsuzuki.com/sustainability"),
    ("Subaru", "https://www.subaru.co.jp/en/csr"),
    ("Mazda", "https://www.mazda.com/en/sustainability"),
    ("Isuzu", "https://www.isuzu.co.jp/sustainability"),
    ("Komatsu", "https://www.komatsu.com/en/sustainability"),
    ("Kubota", "https://www.kubota.com/sustainability"),
    ("Bridgestone", "https://www.bridgestone.com/csr"),
    ("Asahi Kasei", "https://www.asahi-kasei.com/sustainability"),
    ("Toray", "https://www.toray.com/sustainability"),
    ("Teijin", "https://www.teijin.com/sustainability"),
    ("Shin-Etsu Chemical", "https://www.shinetsu.co.jp/en/sustainability"),
    ("Nippon Paper", "https://www.nipponpapergroup.com/english/csr"),
    ("Kirin", "https://www.kirinholdings.co.jp/english/csv"),
    ("Asahi Group", "https://www.asahigroup-holdings.com/sustainability"),
    ("Suntory", "https://www.suntory.com/csr"),
    ("Ajinomoto", "https://www.ajinomoto.com/sustainability"),
    ("Nippon Yusen", "https://www.nyk.com/english/sustainability"),
    
    # South Korea
    ("Samsung", "https://www.samsung.com/global/sustainability"),
    ("Hyundai", "https://www.hyundai.com/worldwide/en/sustainability"),
    ("LG", "https://www.lg.com/global/sustainability"),
    ("SK Group", "https://www.sk.com/en/sustainability"),
    ("POSCO", "https://www.posco.co.kr/homepage/docs/eng6/jsp/sustainability"),
    ("Kia", "https://worldwide.kia.com/int/sustainability"),
    ("Hyundai Steel", "https://www.hyundai-steel.com/en/sustainability"),
    ("Lotte", "https://www.lotte.co.kr/sustainability"),
    ("Hankook Tire", "https://www.hankooktire.com/sustainability"),
    ("Hanwha", "https://www.hanwha.com/en/sustainability"),
    ("GS", "https://www.gs.co.kr/en/sustainability"),
    ("CJ Group", "https://english.cj.net/sustainability"),
    ("Doosan", "https://www.doosan.com/en/sustainability"),
    ("LG Chem", "https://www.lgchem.com/sustainability"),
    ("Samsung SDI", "https://www.samsungsdi.com/sustainability"),
    ("SK Innovation", "https://www.skinnovation.com/sustainability"),
    
    # India
    ("Tata Steel", "https://www.tatasteel.com/sustainability"),
    ("Reliance Industries", "https://www.ril.com/sustainability"),
    ("Hindalco", "https://www.hindalco.com/sustainability"),
    ("JSW Steel", "https://www.jsw.in/sustainability"),
    ("Vedanta", "https://www.vedantalimited.com/sustainability"),
    ("Infosys", "https://www.infosys.com/sustainability"),
    ("Wipro", "https://www.wipro.com/sustainability"),
    ("Mahindra", "https://www.mahindra.com/sustainability"),
    ("Adani", "https://www.adani.com/sustainability"),
    ("ITC Limited", "https://www.itcportal.com/sustainability"),
    ("ONGC", "https://www.ongcindia.com/sustainability"),
    ("Indian Oil", "https://www.iocl.com/sustainability"),
    ("BPCL", "https://www.bharatpetroleum.in/sustainability"),
    ("HPCL", "https://www.hindustanpetroleum.com/sustainability"),
    ("GAIL", "https://www.gailonline.com/sustainability"),
    ("NTPC", "https://www.ntpc.co.in/sustainability"),
    ("Coal India", "https://www.coalindia.in/sustainability"),
    ("SAIL", "https://www.sail.co.in/sustainability"),
    ("NMDC", "https://www.nmdc.co.in/sustainability"),
    ("Hindustan Zinc", "https://www.hzlindia.com/sustainability"),
    ("Jindal Steel", "https://www.jindalsteelpower.com/sustainability"),
    ("Shree Cement", "https://www.shreecement.com/sustainability"),
    ("UltraTech", "https://www.ultratechcement.com/sustainability"),
    ("ACC", "https://www.acclimited.com/sustainability"),
    ("Ambuja Cements", "https://www.ambujacement.com/sustainability"),
    ("Godrej", "https://www.godrej.com/sustainability"),
    ("Asian Paints", "https://www.asianpaints.com/sustainability"),
    ("UPL", "https://www.upl-ltd.com/sustainability"),
    
    # Australia/NZ
    ("BHP", "https://www.bhp.com/sustainability"),
    ("Rio Tinto", "https://www.riotinto.com/sustainability"),
    ("Fortescue", "https://www.fortescue.com/sustainability"),
    ("Woolworths AU", "https://www.woolworthsgroup.com.au/sustainability"),
    ("Fonterra", "https://www.fonterra.com/nz/en/sustainability"),
    
    # Southeast Asia
    ("Petronas", "https://www.petronas.com/sustainability"),
    ("Sime Darby", "https://www.simedarby.com/sustainability"),
    ("Wilmar", "https://www.wilmar-international.com/sustainability"),
    ("Singapore Airlines", "https://www.singaporeair.com/en_UK/sustainability"),
    ("DBS Bank", "https://www.dbs.com/sustainability"),
    ("PTT", "https://www.pttplc.com/en/sustainability"),
    ("Vingroup", "https://www.vingroup.net/en/sustainability"),
    ("Thai Oil", "https://www.thaioilgroup.com/sustainability"),
    ("SCG", "https://www.scg.com/sustainability"),
    ("Indorama Ventures", "https://www.indoramaventures.com/sustainability"),
    ("Charoen Pokphand", "https://www.cpgroupglobal.com/sustainability"),
    ("Thai Union", "https://www.thaiunion.com/sustainability"),
    ("San Miguel", "https://www.sanmiguel.com.ph/sustainability"),
    ("Ayala Corporation", "https://www.ayala.com.ph/sustainability"),
    ("Aboitiz", "https://www.aboitiz.com/sustainability"),
    ("Golden Agri", "https://www.goldenagri.com.sg/sustainability"),
    ("IOI Corporation", "https://www.ioigroup.com/sustainability"),
    ("Sime Darby Plantation", "https://www.simedarbyplantation.com/sustainability"),
    ("Telkom Indonesia", "https://www.telkom.co.id/sustainability"),
    ("Pertamina", "https://www.pertamina.com/sustainability"),
    
    # =========================================================================
    # EUROPE - 150+ Companies
    # =========================================================================
    # UK
    ("BP", "https://www.bp.com/en/global/corporate/sustainability"),
    ("Shell", "https://www.shell.com/sustainability"),
    ("Unilever", "https://www.unilever.com/planet-and-society"),
    ("GSK", "https://www.gsk.com/en-gb/responsibility"),
    ("AstraZeneca", "https://www.astrazeneca.com/sustainability"),
    ("Diageo", "https://www.diageo.com/sustainability"),
    ("Rolls-Royce", "https://www.rolls-royce.com/sustainability"),
    ("BAE Systems", "https://www.baesystems.com/sustainability"),
    ("British American Tobacco", "https://www.bat.com/sustainability"),
    ("Tesco", "https://www.tescoplc.com/sustainability"),
    ("Sainsburys", "https://www.about.sainsburys.co.uk/sustainability"),
    ("Associated British Foods", "https://www.abf.co.uk/responsibility"),
    ("Taylor Wimpey", "https://www.taylorwimpey.co.uk/sustainability"),
    ("British Steel", "https://www.britishsteel.co.uk/sustainability"),
    ("JCB", "https://www.jcb.com/sustainability"),
    ("Jaguar Land Rover", "https://www.jaguarlandrover.com/sustainability"),
    
    # Germany
    ("BASF", "https://www.basf.com/global/en/who-we-are/sustainability"),
    ("Volkswagen", "https://www.volkswagen-group.com/en/sustainability"),
    ("BMW", "https://www.bmwgroup.com/en/sustainability"),
    ("Mercedes-Benz", "https://group.mercedes-benz.com/sustainability"),
    ("Siemens", "https://www.siemens.com/sustainability"),
    ("Bayer", "https://www.bayer.com/en/sustainability"),
    ("ThyssenKrupp", "https://www.thyssenkrupp.com/en/sustainability"),
    ("Covestro", "https://www.covestro.com/sustainability"),
    ("Evonik", "https://corporate.evonik.com/en/sustainability"),
    ("HeidelbergCement", "https://www.heidelbergmaterials.com/en/sustainability"),
    ("Porsche", "https://www.porsche.com/sustainability"),
    ("Audi", "https://www.audi.com/en/sustainability"),
    ("Continental", "https://www.continental.com/sustainability"),
    ("ZF", "https://www.zf.com/sustainability"),
    ("Bosch", "https://www.bosch.com/sustainability"),
    ("SAP", "https://www.sap.com/about/company/purpose-and-sustainability"),
    ("Deutsche Telekom", "https://www.telekom.com/sustainability"),
    ("E.ON", "https://www.eon.com/en/sustainability"),
    ("RWE", "https://www.rwe.com/en/sustainability"),
    ("Lufthansa", "https://www.lufthansagroup.com/sustainability"),
    ("Deutsche Post DHL", "https://www.dpdhl.com/sustainability"),
    ("Henkel", "https://www.henkel.com/sustainability"),
    ("Wacker Chemie", "https://www.wacker.com/sustainable"),
    ("Lanxess", "https://lanxess.com/en/sustainability"),
    
    # France
    ("TotalEnergies", "https://totalenergies.com/sustainability"),
    ("L'Oreal", "https://www.loreal.com/sustainability"),
    ("Danone", "https://www.danone.com/impact"),
    ("Engie", "https://www.engie.com/en/sustainable-development"),
    ("Saint-Gobain", "https://www.saint-gobain.com/en/sustainability"),
    ("Air Liquide", "https://www.airliquide.com/sustainable-development"),
    ("Michelin", "https://www.michelin.com/en/sustainable-development"),
    ("Veolia", "https://www.veolia.com/en/our-purpose/sustainable-development"),
    ("Renault", "https://www.renaultgroup.com/en/sustainability"),
    ("Sanofi", "https://www.sanofi.com/en/our-responsibility"),
    ("Airbus", "https://www.airbus.com/sustainability"),
    ("Thales", "https://www.thalesgroup.com/sustainability"),
    ("Safran", "https://www.safran-group.com/sustainability"),
    ("Schneider Electric", "https://www.se.com/sustainability"),
    ("Alstom", "https://www.alstom.com/sustainability"),
    ("Bouygues", "https://www.bouygues.com/sustainability"),
    ("Vinci", "https://www.vinci.com/vinci.nsf/en/sustainability"),
    ("Pernod Ricard", "https://www.pernod-ricard.com/en/sustainability"),
    ("Carrefour", "https://www.carrefour.com/en/csr"),
    
    # Netherlands/Switzerland
    ("Heineken", "https://www.theheinekencompany.com/sustainability"),
    ("Philips", "https://www.philips.com/sustainability"),
    ("AkzoNobel", "https://www.akzonobel.com/sustainability"),
    ("Nestle", "https://www.nestle.com/sustainability"),
    ("Roche", "https://www.roche.com/sustainability"),
    ("Novartis", "https://www.novartis.com/esg"),
    ("Holcim", "https://www.holcim.com/sustainability"),
    ("Glencore", "https://www.glencore.com/sustainability"),
    ("ABB", "https://global.abb/group/sustainability"),
    ("Sika", "https://www.sika.com/en/sustainability"),
    ("Clariant", "https://www.clariant.com/en/Sustainability"),
    ("Lonza", "https://www.lonza.com/sustainability"),
    ("Givaudan", "https://www.givaudan.com/sustainability"),
    ("DSM", "https://www.dsm.com/sustainability"),
    ("ASML", "https://www.asml.com/sustainability"),
    ("Ahold Delhaize", "https://www.aholddelhaize.com/sustainability"),
    ("Umicore", "https://www.umicore.com/sustainability"),
    ("Solvay", "https://www.solvay.com/sustainability"),
    ("AB InBev", "https://www.ab-inbev.com/sustainability"),
    
    # Nordics
    ("Equinor", "https://www.equinor.com/sustainability"),
    ("Maersk", "https://www.maersk.com/sustainability"),
    ("Orsted", "https://orsted.com/en/sustainability"),
    ("Volvo", "https://www.volvogroup.com/sustainability"),
    ("IKEA", "https://www.ikea.com/global/en/our-sustainability"),
    ("H&M", "https://hmgroup.com/sustainability"),
    ("Stora Enso", "https://www.storaenso.com/sustainability"),
    ("UPM", "https://www.upm.com/sustainability"),
    ("Sandvik", "https://www.sandvik.com/sustainability"),
    ("Atlas Copco", "https://www.atlascopco.com/sustainability"),
    ("SKF", "https://www.skf.com/group/sustainability"),
    ("Electrolux", "https://www.electroluxgroup.com/sustainability"),
    ("Yara", "https://www.yara.com/sustainability"),
    ("Hydro", "https://www.hydro.com/sustainability"),
    ("Neste", "https://www.neste.com/sustainability"),
    ("Fortum", "https://www.fortum.com/sustainability"),
    
    # Italy/Spain
    ("Eni", "https://www.eni.com/en-IT/sustainability"),
    ("Enel", "https://www.enel.com/sustainability"),
    ("Stellantis", "https://www.stellantis.com/en/sustainability"),
    ("Repsol", "https://www.repsol.com/en/sustainability"),
    ("Iberdrola", "https://www.iberdrola.com/sustainability"),
    ("Endesa", "https://www.endesa.com/en/sustainability"),
    ("Acerinox", "https://www.acerinox.com/sustainability"),
    ("Ferrovial", "https://www.ferrovial.com/sustainability"),
    ("Pirelli", "https://www.pirelli.com/sustainability"),
    ("Tenaris", "https://www.tenaris.com/sustainability"),
    ("Prysmian", "https://www.prysmiangroup.com/sustainability"),
    
    # =========================================================================
    # NORTH AMERICA - 180+ Companies
    # =========================================================================
    # Oil & Gas
    ("ExxonMobil", "https://corporate.exxonmobil.com/sustainability-and-reports"),
    ("Chevron", "https://www.chevron.com/sustainability"),
    ("ConocoPhillips", "https://www.conocophillips.com/sustainability"),
    ("Valero", "https://www.valero.com/responsibility"),
    ("Marathon Petroleum", "https://www.marathonpetroleum.com/Responsibility"),
    ("Phillips 66", "https://www.phillips66.com/responsibility"),
    ("Halliburton", "https://www.halliburton.com/sustainability"),
    ("Baker Hughes", "https://www.bakerhughes.com/sustainability"),
    ("Schlumberger", "https://www.slb.com/sustainability"),
    ("Devon Energy", "https://www.devonenergy.com/sustainability"),
    ("Pioneer Natural", "https://www.pxd.com/sustainability"),
    ("EOG Resources", "https://www.eogresources.com/sustainability"),
    ("Occidental Petroleum", "https://www.oxy.com/sustainability"),
    ("Kinder Morgan", "https://www.kindermorgan.com/Pages/responsibility"),
    
    # Chemicals
    ("Dow", "https://corporate.dow.com/en-us/esg"),
    ("DuPont", "https://www.dupont.com/about/sustainability"),
    ("LyondellBasell", "https://www.lyondellbasell.com/sustainability"),
    ("Eastman", "https://www.eastman.com/en/sustainability"),
    ("Huntsman", "https://www.huntsman.com/sustainability"),
    ("PPG", "https://www.ppg.com/en-US/sustainability"),
    ("Sherwin-Williams", "https://sustainability.sherwin-williams.com"),
    ("3M", "https://www.3m.com/3M/en_US/sustainability-us"),
    ("Linde", "https://www.linde.com/sustainability"),
    ("Air Products", "https://www.airproducts.com/company/sustainability"),
    ("Celanese", "https://www.celanese.com/sustainability"),
    ("Westlake Chemical", "https://www.westlake.com/sustainability"),
    ("Albemarle", "https://www.albemarle.com/sustainability"),
    ("FMC Corporation", "https://www.fmc.com/sustainability"),
    ("Mosaic", "https://www.mosaicco.com/sustainability"),
    ("CF Industries", "https://www.cfindustries.com/sustainability"),
    ("Corteva", "https://www.corteva.com/sustainability"),
    
    # Metals & Mining
    ("Nucor", "https://www.nucor.com/sustainability"),
    ("US Steel", "https://www.ussteel.com/sustainability"),
    ("Cleveland-Cliffs", "https://www.clevelandcliffs.com/sustainability"),
    ("Freeport-McMoRan", "https://www.fcx.com/sustainability"),
    ("Newmont", "https://www.newmont.com/sustainability"),
    ("Alcoa", "https://www.alcoa.com/sustainability"),
    ("Steel Dynamics", "https://www.steeldynamics.com/sustainability"),
    ("Commercial Metals", "https://www.cmc.com/sustainability"),
    ("Reliance Steel", "https://www.rsac.com/sustainability"),
    ("Barrick Gold", "https://www.barrick.com/sustainability"),
    ("Southern Copper", "https://www.southerncoppercorp.com/sustainability"),
    ("Novelis", "https://www.novelis.com/sustainability"),
    
    # Auto/Tech
    ("Ford", "https://corporate.ford.com/sustainability"),
    ("GM", "https://www.gm.com/commitments/sustainability"),
    ("Tesla", "https://www.tesla.com/impact"),
    ("Apple", "https://www.apple.com/environment"),
    ("Microsoft", "https://www.microsoft.com/en-us/corporate-responsibility"),
    ("Amazon", "https://sustainability.aboutamazon.com"),
    ("Intel", "https://www.intel.com/content/www/us/en/corporate-responsibility"),
    ("Dell", "https://www.dell.com/en-us/dt/corporate/social-impact"),
    ("Paccar", "https://www.paccar.com/sustainability"),
    ("Cummins", "https://www.cummins.com/sustainability"),
    ("BorgWarner", "https://www.borgwarner.com/sustainability"),
    ("Aptiv", "https://www.aptiv.com/sustainability"),
    ("Lear Corporation", "https://www.lear.com/sustainability"),
    ("Magna International", "https://www.magna.com/sustainability"),
    
    # Paper & Packaging
    ("International Paper", "https://www.internationalpaper.com/sustainability"),
    ("WestRock", "https://www.westrock.com/sustainability"),
    ("Packaging Corp", "https://www.packagingcorp.com/sustainability"),
    ("Sonoco", "https://www.sonoco.com/sustainability"),
    ("Berry Global", "https://www.berryglobal.com/sustainability"),
    ("Sealed Air", "https://www.sealedair.com/sustainability"),
    ("Ball Corporation", "https://www.ball.com/sustainability"),
    ("Crown Holdings", "https://www.crowncork.com/sustainability"),
    
    # Construction & Building
    ("Vulcan Materials", "https://www.vulcanmaterials.com/sustainability"),
    ("Martin Marietta", "https://www.martinmarietta.com/sustainability"),
    ("Eagle Materials", "https://www.eaglematerials.com/sustainability"),
    ("Owens Corning", "https://www.owenscorning.com/sustainability"),
    ("Masco Corporation", "https://www.masco.com/sustainability"),
    
    # Consumer/Retail
    ("Procter & Gamble", "https://us.pg.com/environmental-sustainability"),
    ("Coca-Cola", "https://www.coca-colacompany.com/sustainability"),
    ("PepsiCo", "https://www.pepsico.com/our-impact/sustainability"),
    ("Walmart", "https://corporate.walmart.com/esgreport"),
    ("Costco", "https://www.costco.com/sustainability"),
    
    # Waste Management
    ("Waste Management", "https://sustainability.wm.com"),
    ("Republic Services", "https://www.republicservices.com/sustainability"),
    ("Clean Harbors", "https://www.cleanharbors.com/sustainability"),
    
    # Food/Ag
    ("ADM", "https://www.adm.com/sustainability"),
    ("Cargill", "https://www.cargill.com/sustainability"),
    ("Tyson Foods", "https://www.tysonfoods.com/sustainability"),
    ("Bunge", "https://www.bunge.com/sustainability"),
    ("Hormel Foods", "https://www.hormelfoods.com/responsibility"),
    ("General Mills", "https://www.generalmills.com/responsibility"),
    ("Kellogg", "https://www.kelloggcompany.com/sustainability"),
    ("Mondelez", "https://www.mondelezinternational.com/sustainability"),
    ("Kraft Heinz", "https://www.kraftheinzcompany.com/responsibility"),
    ("Hershey", "https://www.thehersheycompany.com/sustainability"),
    
    # Healthcare & Pharma
    ("Johnson & Johnson", "https://www.jnj.com/sustainability"),
    ("Pfizer", "https://www.pfizer.com/about/responsibility"),
    ("Merck", "https://www.merck.com/company-overview/esg"),
    ("AbbVie", "https://www.abbvie.com/responsibility"),
    ("Bristol-Myers", "https://www.bms.com/about-us/sustainability"),
    ("Eli Lilly", "https://www.lilly.com/sustainability"),
    ("Amgen", "https://www.amgen.com/responsibility"),
    ("Gilead", "https://www.gilead.com/responsibility"),
    ("Biogen", "https://www.biogen.com/responsibility"),
    ("Moderna", "https://www.modernatx.com/responsibility"),
    ("Baxter", "https://www.baxter.com/our-story/corporate-responsibility"),
    ("Medtronic", "https://www.medtronic.com/sustainability"),
    ("Abbott", "https://www.abbott.com/responsibility"),
    
    # =========================================================================
    # LATIN AMERICA - 50+ Companies
    # =========================================================================
    # Brazil
    ("Petrobras", "https://petrobras.com.br/en/society-and-environment"),
    ("Vale", "https://www.vale.com/sustainability"),
    ("JBS", "https://jbs.com.br/en/sustainability"),
    ("Natura", "https://www.natura.com.br/sustentabilidade"),
    ("Suzano", "https://www.suzano.com.br/en/sustainability"),
    ("Gerdau", "https://www.gerdau.com/sustainability"),
    ("Braskem", "https://www.braskem.com.br/sustainability"),
    
    # Mexico
    ("Pemex", "https://www.pemex.com/en/sustainability"),
    ("CEMEX", "https://www.cemex.com/sustainability"),
    ("Grupo Bimbo", "https://grupobimbo.com/en/sustainability"),
    ("Femsa", "https://www.femsa.com/en/sustainability"),
    
    # Chile/Argentina/Colombia
    ("Codelco", "https://www.codelco.com/sustainability"),
    ("YPF", "https://www.ypf.com/sustainability"),
    ("Ecopetrol", "https://www.ecopetrol.com.co/sustainability"),
    
    # =========================================================================
    # AFRICA - 60+ Companies
    # =========================================================================
    # South Africa
    ("Sasol", "https://www.sasol.com/sustainability"),
    ("Anglo American", "https://www.angloamerican.com/sustainability"),
    ("Gold Fields", "https://www.goldfields.com/sustainability"),
    ("Sappi", "https://www.sappi.com/sustainability"),
    ("MTN", "https://www.mtn.com/sustainability"),
    ("Sibanye-Stillwater", "https://www.sibanyestillwater.com/sustainability"),
    ("Impala Platinum", "https://www.implats.co.za/sustainability"),
    ("Harmony Gold", "https://www.harmony.co.za/sustainability"),
    ("AngloGold Ashanti", "https://www.anglogoldashanti.com/sustainability"),
    ("Exxaro", "https://www.exxaro.com/sustainability"),
    ("Kumba Iron Ore", "https://www.kumba.co.za/sustainability"),
    ("Nedbank", "https://www.nedbank.co.za/sustainability"),
    ("Standard Bank", "https://www.standardbank.com/sustainability"),
    ("Vodacom", "https://www.vodacom.com/sustainability"),
    ("Shoprite", "https://www.shopriteholdings.co.za/sustainability"),
    ("Tiger Brands", "https://www.tigerbrands.com/sustainability"),
    ("AECI", "https://www.aeciworld.com/sustainability"),
    ("PPC", "https://www.ppc.co.za/sustainability"),
    ("Bidvest", "https://www.bidvest.com/sustainability"),
    ("Barloworld", "https://www.barloworld.com/sustainability"),
    
    # Nigeria
    ("Dangote", "https://www.dangote.com/sustainability"),
    ("Nigerian Breweries", "https://www.nbplc.com/sustainability"),
    ("Lafarge Africa", "https://www.lafarge.com.ng/sustainability"),
    ("BUA Group", "https://www.buagroup.com/sustainability"),
    ("Nestle Nigeria", "https://www.nestle-cwa.com/sustainability"),
    ("MTN Nigeria", "https://www.mtn.ng/sustainability"),
    ("Seplat", "https://www.seplatenergy.com/sustainability"),
    
    # East Africa
    ("Safaricom", "https://www.safaricom.co.ke/sustainability"),
    ("East African Breweries", "https://www.eabl.com/sustainability"),
    ("Bamburi Cement", "https://www.bamburi.co.ke/sustainability"),
    ("KCB Group", "https://www.kcbgroup.com/sustainability"),
    ("Equity Group", "https://www.equitygroup.com/sustainability"),
    
    # North Africa
    ("Sonelgaz", "https://www.sonelgaz.dz/sustainability"),
    ("Sonatrach", "https://www.sonatrach.com/sustainability"),
]

# Export count
if __name__ == "__main__":
    print(f"Total companies: {len(COMPANIES)}")
    
    regions = {
        "MENA": 0, "Asia": 0, "Europe": 0, 
        "North America": 0, "Latin America": 0, "Africa": 0
    }
    
    # Simple estimation based on list order
    print(f"\nCompany list ready for: 10 years (2015-2024)")
    print(f"Potential downloads: {len(COMPANIES) * 10}")
